### ISSUE TITLE
SofarSolar HYD 5KTL-EP works!

### ISSUE THREAD

**Issue by jrap1245** [serek4/node-red-sofar-inverter#13]
Inverter : SofarSolar HYD 5KTL-EP 
Hardware: V003
Software: V030054
Protocol: 1.07
Buffer length: 1445

I had to use config_hide.html to configure server. 
Did'nt have time to check everything but main inverter data are ok, but I don't receive any info about battery.

Thank you for the great job !

**Comment by serek4** [comment]
So it looks like it sends the same data frame as SofarSolar 4.4KTLX-G3
