### ISSUE TITLE
Forward data from logger to dockerized Node Red

### ISSUE THREAD

**Issue by ilexpl01** [serek4/node-red-sofar-inverter#8]
Hi,

My Node Red is running as docker on my Synology NAS. Only single TCP port 1880 is exposed.

Can I get an advise how to forward port 10000 to  NR ?

BR
Mikolaj

**Comment by serek4** [comment]
simply add port 10000:10000 TCP to your docker container and make sure it is not blocked by firewall

this is my docker compose for example
````compose
services:
  nodered:
    container_name: nodered
    image: nodered/node-red:latest-18
    restart: unless-stopped
    ports:
      - "1880:1880"
      - "10000:10000"
    volumes:
      - ./data:/data
    environment:
      - TZ=Europe/Warsaw
````

**Comment by ilexpl01** [comment]
Dziękuję 😊
