### ISSUE TITLE
Decode KTLX-G3

### ISSUE THREAD

**Issue by pekae** [serek4/node-red-sofar-inverter#9]
A new Version of the KTLX has arrived. the G3 

I can not decode messages from logger from that device - Start seems to be same - can decode Logger-Serial, but no actuel values from inverter 

Any information for new invertermodell ?

**Comment by serek4** [comment]
check [node-red-subflow.json](https://github.com/serek4/node-red-sofar-inverter/blob/dev-KTL-X-G3/node-red-subflow.json) from  [dev-KTL-X-G3](https://github.com/serek4/node-red-sofar-inverter/tree/dev-KTL-X-G3)  branch with added code proposed by @grzegorzgrzeszkowiak in #10 and let me know if it is working for you

**Comment by pekae** [comment]
It works - great, thanks Mit freundlichen GrußPeter KästnerAm 03.11.2022 um 21:09 schrieb serek4 ***@***.***>:﻿
check node-red-subflow.json from  dev-KTL-X-G3  branch with added code proposed by @grzegorzgrzeszkowiak in #10 and let me know if it is working for you
